export const PRODUCTS_LIST = 'PRODUCTS_LIST'
export const PRODUCTS_ADD = 'PRODUCTS_ADD'
export const PRODUCTS_UPDATE = 'PRODUCTS_UPDATE'
export const PRODUCTS_REMOVE = 'PRODUCTS_REMOVE'

export default {
  PRODUCTS_LIST,
  PRODUCTS_ADD,
  PRODUCTS_UPDATE,
  PRODUCTS_REMOVE,
}