export const CATEGORIES_LIST = 'CATEGORIES_LIST'
export const CATEGORIES_ADD = 'CATEGORIES_ADD'
export const CATEGORIES_UPDATE = 'CATEGORIES_UPDATE'
export const CATEGORIES_REMOVE = 'CATEGORIES_REMOVE'

export default {
  CATEGORIES_LIST,
  CATEGORIES_ADD,
  CATEGORIES_UPDATE,
  CATEGORIES_REMOVE,
}